package core

type Schema interface {
	GetID() string
	SetCreatedAt()
	SetUpdatedAt()
	SetDeletedAt()
	UnsetDeletedBy()
	SetCreatedBy(string)
	SetUpdatedBy(string)
	SetDeletedBy(string)
	SetAccountID(string)
}

type AutoGenerated interface {
	Generate() error
}
