package core

import (
	"reflect"

	"github.com/aritradevelops/authinfinity/server/internal/authn"
	"github.com/aritradevelops/authinfinity/server/internal/pkg/validator"
	"github.com/gofiber/fiber/v2"
)

// Service defines generic CRUD operations for any schema type.
type Service[S Schema] interface {
	List(*fiber.Ctx) (*PaginatedResponse[S], error)
	Create(*fiber.Ctx) (string, error)
	Update(*fiber.Ctx) (bool, error)
	View(*fiber.Ctx) (S, error)
	Delete(*fiber.Ctx) (bool, error)
}

// BaseService implements the generic Service interface using a repository.
type BaseService[S Schema] struct {
	repository Repository[S]
}

// NewService returns a new BaseService instance.
func NewService[S Schema](repository Repository[S]) Service[S] {
	return &BaseService[S]{repository: repository}
}

// List retrieves paginated results based on query parameters.
func (s *BaseService[S]) List(c *fiber.Ctx) (*PaginatedResponse[S], error) {
	listOpts, err := NewListOptions(c)
	if err != nil {
		return nil, NewBadRequestError(c)
	}
	return s.repository.List(listOpts)
}

// Create inserts a new record.
func (s *BaseService[S]) Create(c *fiber.Ctx) (string, error) {
	var data S
	if err := c.BodyParser(&data); err != nil {
		return "", NewBadRequestError(c)
	}

	if authUser, err := authn.GetAuthUser(c); err == nil {
		data.SetCreatedAt()
		data.SetCreatedBy(authUser.ID)
		data.SetAccountID(authUser.AccountID)
	}

	if generator, ok := any(data).(AutoGenerated); ok {
		if err := generator.Generate(); err != nil {
			return "", NewInternalServerError(c)
		}
	}

	if errs := validator.Validate(data, c); errs != nil {
		return "", NewRequestValidationError(c, errs)
	}

	return s.repository.Create(data)
}

// Update modifies an existing record by ID.
func (s *BaseService[S]) Update(c *fiber.Ctx) (bool, error) {
	id := c.Params("id")

	var data S
	if err := c.BodyParser(&data); err != nil {
		return false, NewBadRequestError(c)
	}

	if authUser, err := authn.GetAuthUser(c); err == nil {
		data.SetUpdatedAt()
		data.SetUpdatedBy(authUser.ID)
	}

	if errs := validator.Validate(data, c); errs != nil {
		return false, NewRequestValidationError(c, errs)
	}

	filter := Filter{"id": id, "deleted_at": nil}
	return s.repository.Update(filter, data)
}

// View retrieves a single record by ID.
func (s *BaseService[S]) View(c *fiber.Ctx) (S, error) {
	id := c.Params("id")
	filter := Filter{"id": id, "deleted_at": nil}

	var data S
	err := s.repository.View(filter, &data)
	return data, err
}

// Delete performs a soft delete by setting deleted_at and deleted_by.
func (s *BaseService[S]) Delete(c *fiber.Ctx) (bool, error) {
	id := c.Params("id")

	schema := reflect.New(reflect.TypeFor[S]().Elem())
	data := schema.Interface().(S)

	if authUser, err := authn.GetAuthUser(c); err == nil {
		data.SetDeletedAt()
		data.SetDeletedBy(authUser.ID)
	}

	filter := Filter{"id": id, "deleted_at": nil}
	return s.repository.Update(filter, data)
}
